name = "inframap"
main = "src/index.ts"
compatibility_date = "2023-01-06"
route = "inframap.stefanpuia.co.uk/*"
usage_model = "bundled"
workers_dev = false

[vars]
API_URL = "https://inframap-api.stefanpuia.co.uk"
FRONTEND_URL = "https://inframap.pages.dev/"

[triggers]
crons = []
